### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by bcheggeseth** [KudzaiDhewa/Stat212_Project1#1]
**Requested File Structure**
- [x] code
- [x] data
- [x] planning with Milestone1.qmd  

**.gitignore**
- [ ] Created a .gitignore file
- [ ] Contains all of the request files in it

**Milestone2.qmd**
- [ ] Progress on the stated plan
- [ ] Future plan for Milestone 3
- [ ] Included sessionInfo() at the end of qmd files

General Feedback:

- Very little work in Github.

Collaboration:

- I'm going to check git commits every milestone to ensure there are distinct individual contributions.
