### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by lsokolew** [KudzaiDhewa/Stat212_Project1#2]
**Requested File Structure**
- [x] results folder 
- [x] with Milestone3-Blog.qmd 
- [x] with rendered html
- [ ] Included sessionInfo() at the end of qmd files
- it seems to only be in your milestone 2 qmd 

**Progress from Milestone 2**
- [x] Progress on the stated plan

**Milestone3-Blog**
images aren’t appearing in your HTML; try adding `embed-resources: true`, or checking your image file paths
- [ ] < 1000 words
- ~1250
- [x] Motivate the importance of the topic
- defining PUBG/giving a bit more context in future reports would be helpful for those unfamiliar with your topic!
- [x] Lead the reader through the rationale for the narrowing/focusing of the scope via the main 2-3 broad questions
- [x] Tie results (plots and modeling output) to the broad questions and explain how all results fit together
- [x] End with main takeaways, limitations with regard to the data context and ethical considerations, and future directions
- I’m curious what limitations there are in the data you’re working with- is there any missing or inconsistent data? What are other limitations to the scope of your analysis?
