### ISSUE TITLE
Milestone 5

### ISSUE THREAD

**Issue by KudzaiDhewa** [KudzaiDhewa/Stat212_Project1#3]
**Research Questions Summary**

The big picture of our project is to figure out ways to maximize a player’s survival chances in PUBG. If a player’s team is the last team standing, we will be referring to them as the chicken dinner winner. In total we have 3 research questions that revolve around exploring tactics skillful players apply to survive the longest, or to effectively participate in combat to directly eliminate other teams to secure the top spots. Specifically, we aim to explore data retrieved from 3 important endpoints of the PUBG API: lifetime stats, weapon master and survival mastery. We anticipate that by looking at metrics such as killCount, KnockCount, weaponUsed, modeOfTransport, etc, we will be able to come up with some visualizations that effectively demonstrate strong correlations between a skill set and survival probability.

**Planned Digital Artifact**

Due to the nature of our data, which is a survival game, we agree that a blog would be our best option for our digital artifact. The rationale behind this decision is that, compared to other data such as the census data, where variable interpretability can be easy and straightforward and any user can freely pick and choose filters in a shiny app, data specific to a game can be a little harder to interpret, unless you are a gaming enthusiast. Therefore, a blogpost written by expert players, like we are, will be most effective in conveying the most interesting observations and in explaining why such observations are worth paying attention to.

In general, we will be working on a blog that tells a story about PUBG players’ performances through the analysis of their lifetime statistics, weapon mastery and survival mastery. This will be done through a variety of visualizations and descriptive text mainly focusing on key takeaways that could help both players and game developers enhance the gaming experience for PUBG and similar games!

**Tasks**

Due By 12/8

- [ ] Lifetime stats analysis and visualizations (Kudzai)
- [ ] Weapon mastery analysis and visualizations (Hanna)
- [ ] Fix the broken function for iterating over IDs to pull weapons mastery as a list of dataframes
- [ ] Refine the semi-constructed function for cleaning that data
- [ ] Survival mastery analysis and visualizations (Tam)

Due By 12/7

- [ ] Make data viz
- [ ] Fix everything that doesn’t work
- [ ] Put together the final qmd (Tam, Kudzai & Hanna
